server:
  port: 41236 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-biz # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ex_cloud?serverTimezone=GMT%2B8
    username: root
    password: 123456



  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址



    #    #mybatis日志
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##        # 设置日志级别
##        logging:
##          level:
##            root: ERROR